export const placeholderContent = `
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas leo tortor, elementum vel tempus vel, luctus at elit. Maecenas ac mattis urna. Praesent a elementum ipsum. Praesent laoreet molestie tincidunt. Donec ullamcorper, eros quis porta dapibus, tellus mi gravida est, sagittis posuere velit nulla vitae massa. Suspendisse consectetur, dolor sit amet scelerisque cursus, dolor neque sodales ex, vitae facilisis ante lectus non turpis. Duis mattis porttitor lectus. Aliquam ac pharetra justo. Fusce elementum velit sed mauris scelerisque pretium at sit amet odio.
  </p>
  <p>
    Maecenas ut urna ipsum. Mauris fringilla massa ut varius lobortis. Nunc molestie nec erat nec consectetur. Mauris sodales vestibulum dolor non mollis. Cras vitae laoreet odio. Quisque ac ipsum mattis, pretium nisl pellentesque, aliquet justo. In posuere tincidunt ligula quis iaculis. Etiam justo ligula, ultrices pulvinar ante ac, finibus luctus magna. Vivamus aliquam libero vitae mi mollis, ac elementum ex vestibulum. Proin at maximus est. Pellentesque eu nibh malesuada, sagittis elit ac, molestie eros. Mauris arcu mauris, tempor fringilla ligula quis, viverra mattis justo.
  </p>
  <p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi suscipit sodales semper. Maecenas volutpat nibh massa, sed auctor urna aliquet egestas. Sed aliquet leo tellus, et sodales leo porttitor ac. Etiam lectus sem, scelerisque ac arcu sed, rhoncus aliquet quam. Duis massa ex, condimentum at metus ac, cursus rhoncus mauris. In egestas, mauris semper volutpat volutpat, dolor dui pretium lacus, in efficitur metus erat et metus. Suspendisse vestibulum nibh in dolor sollicitudin eleifend. Nunc laoreet mauris in mi sollicitudin elementum. Nam ut gravida ex, eget egestas sapien. Donec quis pharetra felis. Donec orci mi, ultrices eget efficitur non, consequat sit amet diam. Curabitur iaculis malesuada convallis. Phasellus eget metus sapien. Duis sed tellus facilisis, tempor diam vel, interdum velit. In diam tortor, fringilla eu justo vitae, aliquam ornare tellus.
  </p>
  <p>
    Fusce ullamcorper ante eu nisi fermentum tincidunt fringilla eget nunc. Morbi vel lacus sed turpis volutpat consectetur ac nec lectus. Pellentesque eu pulvinar sapien, in pretium arcu. Nam finibus libero a turpis egestas, ornare suscipit lorem dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus eu sapien nec lectus dignissim consectetur sed commodo felis. Vestibulum lorem augue, ultrices in enim id, efficitur posuere tellus.
  </p>
  <p>
    Quisque blandit ac leo ac condimentum. In dolor dolor, rhoncus vitae pharetra et, ultrices viverra arcu. In sit amet mi eros. Integer ut justo nec erat euismod pellentesque. Quisque enim nisl, elementum eget vulputate vitae, pharetra in velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis sodales sit amet erat eget facilisis. Mauris odio odio, vehicula vel pulvinar quis, sagittis sed ante. Maecenas blandit dui ligula, vitae sollicitudin metus ultrices sed. Nullam viverra nulla vitae odio tincidunt, facilisis tristique elit rhoncus. Donec quis nisi ac tortor ullamcorper efficitur id at erat. Suspendisse maximus, augue et condimentum rutrum, augue metus vehicula tortor, ut laoreet lectus arcu at sem.
  </p>
  <p>
    Integer et diam eleifend nunc interdum faucibus. Donec bibendum neque ut aliquet auctor. Nulla eleifend sit amet ipsum eu varius. Aliquam fringilla ornare nisi, quis consequat risus cursus ac. Nunc porta iaculis viverra. Praesent vulputate odio nunc, nec rutrum magna rhoncus ac. Integer bibendum ipsum cursus, bibendum risus id, consequat mauris. Vivamus et aliquet augue. Duis vel odio ultricies, auctor est at, ultrices ligula. Sed egestas, nisi nec vehicula blandit, mauris lectus mollis ipsum, a varius lectus orci nec ex. Fusce eu quam eu nibh sodales vulputate. In hac habitasse platea dictumst. Maecenas bibendum eget nunc eget mattis.
  </p>
`
